"""empty message

Revision ID: 661921f1e8b4
Revises: 4602754b1021
Create Date: 2023-02-24 08:21:33.913838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661921f1e8b4'
down_revision = '4602754b1021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
